---
title: "EDS 221 Day 4 Activities"
output: html_document
date: "2023-08-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

## Task 1

```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
transects <- c("Transect A", "Transect B", "Transect C")

# write a nested for loops that creates a matrix that contains the following (refer to matrix in task 1)

matrix_1 <- matrix(nrow = 7, ncol = 3)

for (i in seq_along(weekdays)) {
  for (j in seq_along(transects)) {
    temp <- paste(weekdays[i], "-", transects[j])
    matrix_1[i, j] <- temp
  }
}
```

## Task 2

```{r}
# write a function called "force" that calculates a force (in Newtons), given inputs of mass (in kg), and acceleration (in m/s^2), and returns a statement

force <- function(mass, acceleration) {
  paste("The resulting force is", mass * acceleration, "Newtons")
}

force(20, 22)
```

## Task 3

```{r}
# fish weight relationship - W = a * L ^ b
# L- length in centimeters, W = expected weight in grams, a and b are species-dependent parameters

fish_parms <- data.frame(sci_name = c("Chanos chanos", "Sphyaena barracuda", "Caranx ignobilis"),
                         common_name = c("Milkfish", "Great barracuda", "Giant trevally"),
                         a_est = c(.0905, .0181, .0353),
                         b_est = c(2.52, 3.27, 3.05))

fish_weight <- function(fish_name, tot_length) {
  fish_sub <- filter(fish_parms, common_name == fish_name)
  fish_sub$a_est * (tot_length) ^ fish_sub$b_est
}

fish_weight("Great barracuda", 30)

# create a vector of lengths by increments of 1 and see if you can calculate the weight over a range of lengths

fish_lengths <- seq(from = 0, to = 30, by = 1)

milkfish_weights <- fish_weight("Milkfish", fish_lengths)

milkfish_weights
```

# Task 4

```{r}
# P = power, H = wave height in meters, T is wave period in seconds

wave_power <- function(wave_height, period) {
  0.5 * ((wave_height) ^ 2) * period
}

wave_power(wave_height = 5, period = 16)

# use wave_power to approximate wave power for a period of 8 seconds, over a range of wave heights from 0-3 meters by increments of .2 meters

wave_range <- seq(from = 0, to = 3, by = 0.2)

wave_power(wave_range, 8)
```

# Task 5

```{r}
wave_power_Brenville <- function(wave_height, period, depth) {
  if (depth > 12) {
    print(0.5 * ((wave_height) ^ 2) * period)
    message("P_deep used")
  } 
  if (depth <= 12) {
    message("P_shallow used")
    0.81 * ((wave_height) ^ 2) * period
  }
}

wave_power_Brenville(wave_height = 15, period = 8, depth = 15)
```
